import { z } from "zod";

export const ValidateProfileSchema = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  birthDate: z.string().optional(),
  sex: z.string().optional(),
  nationality: z.string().optional(),
  residenceCountry: z.string().optional(),
  language: z.string().optional(),
  studyLevel: z.string().optional(),
  obtainedDiploma: z.string().optional(),
  diplomaYear: z.string().optional(),
  specialty: z.string().optional(),
  generalAverage: z.string().optional(),
  strongSubjects: z.string().optional(),
  academicSkills: z.string().optional(),
  academicField: z.string().optional(),
  targetDegree: z.string().optional(),
  spokenLanguages: z.string().optional(),
  languageLevels: z.string().optional(),
  desiredField: z.string().optional(),
  desiredFormationType: z.string().optional(),
  preferredUniversities: z.string().optional(),
  preferredStudyLanguage: z.string().optional(),
  estimatedBudget: z.string().optional(),
  currentInstitution: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  country: z.string().optional(),
  bio: z.string().optional(),
  avatarUrl: z.string().optional(),
  academicDocuments: z.string().optional(),
  academicInterests: z.string().optional(),
  personalInterests: z.string().optional()
});
